version: '3.4'

services:
  paymentgateway-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GATEWAYSETTINGS__CKOBANK__ENDPOINT=http://ckobank/
      - MONGOSETTINGS__CONNECTIONSTRING=mongodb://mongo:27017/PAYMENTS_GATEWAY
    ports:
      - "5001:80"

  ckobank:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"

  cardtokenizer-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"
